// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:app/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: RbbDefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class RbbDefaultFirebaseOptions extends DefaultFirebaseOptions {
  @override
  FirebaseOptions get web => const FirebaseOptions(
        apiKey: 'AIzaSyDQ602HL7KxY6C1JcQNoCMuL144liMuMHQ',
        appId: '1:555741673136:web:07110fe17e293cc0822d75',
        messagingSenderId: '555741673136',
        projectId: 'ramzibazzaz-332dd',
        authDomain: 'ramzibazzaz-332dd.firebaseapp.com',
        storageBucket: 'ramzibazzaz-332dd.appspot.com',
        measurementId: 'G-8ZL3LK1TKN',
      );

  @override
  FirebaseOptions get android => const FirebaseOptions(
        apiKey: 'AIzaSyBrn-ixFPt6ioLzEVEH3AmfDu3_bIHkC58',
        appId: '1:555741673136:android:ac1245dc885e7dc6822d75',
        messagingSenderId: '555741673136',
        projectId: 'ramzibazzaz-332dd',
        storageBucket: 'ramzibazzaz-332dd.appspot.com',
      );

  @override
  FirebaseOptions get ios => const FirebaseOptions(
        apiKey: 'AIzaSyAREfY3mJdJFOKZRNWaekdvbBgJbS2eKR8',
        appId: '1:555741673136:ios:0722d03a6d2a7f77822d75',
        messagingSenderId: '555741673136',
        projectId: 'ramzibazzaz-332dd',
        storageBucket: 'ramzibazzaz-332dd.appspot.com',
        iosBundleId: 'com.techeye.ramzebazzaz',
      );
}
