import 'dart:async';
import 'dart:io';
import 'dart:math' hide log;

import 'package:app/core/network_checker/connection_checker.dart';
import 'package:app/core/shared/imports.dart';
import 'package:app/feature/account/presentation/bloc/account/account_bloc.dart';
import 'package:app/feature/account/presentation/views/login_screen.dart';
import 'package:app/feature/app_setting/data/model/setting_model.dart';
import 'package:app/feature/loading_more/bloc/loading_more_bloc.dart';
import 'package:app/firebase_options.dart';
import 'package:app/kostolog_firebase_options.dart';
import 'package:app/localization/app_local.dart';
import 'package:app/rbb_firebase_options.dart';
import 'package:app/theme/dark_theme.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:html/parser.dart';
import 'package:intl/intl.dart' show Bidi, NumberFormat;

export 'package:app/alerts_and_toasts/alerts/export.dart';
export 'package:app/alerts_and_toasts/toast/export_toast.dart';
export 'package:app/core/error/failures.dart';
export 'package:app/core/model/meta_model.dart';
export 'package:app/core/model/reposne_list.dart';
export 'package:app/core/model/unit_model.dart';
export 'package:app/gen/assets.gen.dart';
export 'package:app/injections.dart';
export 'package:collection/collection.dart';
export 'package:equatable/equatable.dart';

part '../../localization/translate_keys.dart';
part '../../theme/app_colors.dart';
part 'close_keyboard.dart';
part 'connection_checker_cubit.dart';
part 'constants.dart';
part 'context_extension.dart';
part 'date_helpers.dart';
part 'debouncer.dart';
part 'either.dart';
part 'end_points.dart';
part 'enums.dart';
part 'env.dart';
part 'format_price.dart';
part 'functions.dart';
part 'helpers.dart';
part 'int_extension.dart';
part 'logger.dart';
part 'paginations_helper.dart';
part 'responsev.dart';
part 'string_extension.dart';
part 'values_checker.dart';
